# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pps < Formula
  desc "Parallel port scanner, not intended for real use"
  homepage "https://github.com/haroldadmin/pps"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/haroldadmin/pps/releases/download/0.0.4/pps_0.0.4_Darwin_arm64.tar.gz"
      sha256 "30f1118ae71d6e42e1a2afe3984e770a46cad88a4d0374e245f0cf0b8d2c2af9"

      def install
        bin.install "pps"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/haroldadmin/pps/releases/download/0.0.4/pps_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "9d3010d0a082db894e99244ba988a384db1d4ee6cd808a83b9f09ccdd5e79474"

      def install
        bin.install "pps"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/haroldadmin/pps/releases/download/0.0.4/pps_0.0.4_Linux_x86_64.tar.gz"
      sha256 "ac5c5ebd40aef50be1bfc9df6019eb8a8faafdcd3cd7ca7b339241a31004fb31"

      def install
        bin.install "pps"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/haroldadmin/pps/releases/download/0.0.4/pps_0.0.4_Linux_arm64.tar.gz"
      sha256 "3c80c33f1e5654bc78453d8b0c0f7f95583b6642300c3d0fa9b63bf23c2352d4"

      def install
        bin.install "pps"
      end
    end
  end
end
